### ISSUE TITLE
Potential Memory Leak 1.0.0.109 nightly

### ISSUE THREAD

**Issue by randycasburn** [AdguardTeam/AdGuardVPNForMac#6]
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X ] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard VPN version:**
  - 1.0.0.109 nightly
- **VPN mode:**
  - 
- **Operating system and version:**
  - macOS Big Sur 11.3.1
- **Other network-level software:**
  - AdGuard for Mac

### Expected Behavior

Consumes a reasonable amount of memory and CPU utilization

### Actual Behavior

1. High CPU usage
2. More and more memory consumed over time until all physical memory is consumed

### Screenshots

Each of these taken within a few minutes of each other.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/1176839/119690141-099cf400-be0f-11eb-8672-df4c6cff3f51.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/1176839/119690496-5c76ab80-be0f-11eb-8055-976105ebb4ac.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/1176839/119690851-a8c1eb80-be0f-11eb-9869-be8a3c86d0f9.png">

### Additional Information

None

**Comment by randycasburn** [comment]
Resolution: fixed, Status: resolved. -- Great news! Any idea when an update will be pushed? Thanks for your attention to this.

Randy

**Comment by ameshkov** [comment]
@randycasburn hopefully, today

**Comment by Chinaski1** [comment]
@randycasburn 

We are pleased to announce that we have released an update to [117 Nightly](https://adguard-vpn.com/en/beta.html) which solves this issue.

I would appreciate it if you could install the latest Nightly version and confirm that the issue no longer occurs.

**Comment by randycasburn** [comment]
Unfortunately I have bad news. The high CPU utilization and memory consumption continues:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/1176839/122492702-db44ab80-cfab-11eb-94ad-6b4288c1aae1.png">

**Comment by ameshkov** [comment]
@randycasburn quick question - what log level do you have?

**Comment by randycasburn** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/1176839/122801337-96f62b80-d289-11eb-9e22-810f1f229b7b.png">

**Comment by randycasburn** [comment]
Yep - that did it. Set to "Record by default" and it is now very well behaved!! I recommend leaving this open as the problem persists (unless that is expected for troubleshooting purposes).

**Comment by ameshkov** [comment]
This is our mistake that the logging level is set to "Record everything" by default, it writes info about every network packet to the local log file in this case and it makes it use x10 more CPU than normal.

**Comment by randycasburn** [comment]
Where is that log so I can delete it! LOL

**Comment by ameshkov** [comment]
Look here: `~/Library/Group\ Containers/TC3Q7MAJXF.com.adguard.mac/Library/Logs/com.adguard.mac.vpn`

**Comment by randycasburn** [comment]
thanks for you attention to this - and it's my pleasure to help.
